# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6bb00de0ce45b45a7013091d3d2f834210296ec971e267858e145c889874bf5cb0e5cbead0f8c392813adcc361c53e476adfd50d49f6f2eaca6518e462db6b1

test:
  secret_key_base: 9729f11af863e268451d1f88ac02e1a9f021e4351907469939013a76c394fa0d24ce3ca6ef495c559caaa4ba66050672d1702c51a236c832cd431a0e193ca48d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
